#include "stdafx.h"
#include "PE/PEHeader.h"

LIBPE_NAMESPACE_BEGIN

LIBPE_FORCE_TEMPLATE_REDUCTION_CLASS(PEDosHeaderT);
LIBPE_FORCE_TEMPLATE_REDUCTION_CLASS(PENtHeadersT);
LIBPE_FORCE_TEMPLATE_REDUCTION_CLASS(PEFileHeaderT);
LIBPE_FORCE_TEMPLATE_REDUCTION_CLASS(PEOptionalHeaderT);

LIBPE_NAMESPACE_END
